### ISSUE TITLE
拉起训练后卡在第一组batch，配置文件参数问题

### ISSUE THREAD

**Issue by yyoean** [LucaOne/LucaOne#33]
作者大人，我看到您不久前更新了配置文件的注释，但是我有些无法理解
![image](https://github.com/user-attachments/assets/06888c3c-5aa9-4a6a-a6d9-ae0f95a61c42)
比如图中51是对52行的注释，我理解的意思是loss_logging_steps是gradient_accumulation_steps与loss_logging_steps的最小公倍数？
但是loss_logging_steps是自己的公倍数有什么意义？
而且注释中的“这里是4000”与下面的1000不匹配。

因为我在拉起训练的时候，发现用您给的默认的参数，训练卡在第一组batch很久
![image](https://github.com/user-attachments/assets/a9725634-134e-48dc-8a9b-f604fe1a289b)
经过很长时间报下面的错
Training, Epoch: 0001, Batch: 000032, Sample Num: 32, Cur Loss: 15.14121819, Avg Loss: 20.39010298EI9999: Inner Error!
EI9999: 2024-09-19-03:24:21.884.546  The error from device(chipId:0, dieId:0), serial number is 27, hccl fftsplus task timeout occurred during task execution, stream_id:4, sq_id:4, task_id:18848, stuck notify num:1, timeout:1836.[FUNC:ProcessStarsHcclFftsPlusTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1436]
        TraceBack (most recent call last):
        The 0 stuck notify wait context info:(context_id=10, notify_id=38).[FUNC:ProcessStarsHcclFftsPlusTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1443]
        The error from device(chipId:0, dieId:0), serial number is 28, event wait timeout occurred during task execution, stream_id:2, sq_id:2, task_id:57714, event_id=847, timeout=1868.[FUNC:ProcessStarsWaitTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1389]
        Task execute failed, device_id=0, stream_id=2, task_id=57714, flip_num=2, task_type=3(EVENT_WAIT).[FUNC:GetError][FILE:stream.cc][LINE:1082]
        rtStreamSynchronize execute failed, reason=[task timeout][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
        synchronize stream failed, runtime result = 107020[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]

Inner error, see details in Ascend logs.EH9999: Inner Error!
        rtStreamSynchronizeWithTimeout execute failed, reason=[task timeout][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
EH9999: 2024-09-19-03:24:21.928.670  synchronize stream failed, runtime result = 107020[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]

所以我推测是我的参数设置不太对，我尝试了把gradient_accumulation_steps设置为1，好像可以拉起训练，所以想问下这些参数的关系？

**Comment by yyoean** [comment]
> > 作者大人，我看到您不久前更新了配置文件的注释，但是我有些无法理解 ![image](https://private-user-images.githubusercontent.com/180263903/368829281-06888c3c-5aa9-4a6a-a6d9-ae0f95a61c42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjA3ODEsIm5iZiI6MTcyNjcyMDQ4MSwicGF0aCI6Ii8xODAyNjM5MDMvMzY4ODI5MjgxLTA2ODg4YzNjLTVhYTktNGE2YS1hNmQ5LWFlMGY5NWE2MWM0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNDM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmZmNjE4MThkOTNlYjFmYmMwZDhhZjZjN2U0NDY3MTAzNzE4Y2JmNjk3OTI3ZTRiYTEzOWRlMGNlYjJiNDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8EVM7ng7O3hMp-cPlujRPXsPR-QbZfV1JSHY9pfJF0U) 比如图中51是对52行的注释，我理解的意思是loss_logging_steps是gradient_accumulation_steps与loss_logging_steps的最小公倍数？ 但是loss_logging_steps是自己的公倍数有什么意义？ 而且注释中的“这里是4000”与下面的1000不匹配。
> > 因为我在拉起训练的时候，发现用您给的默认的参数，训练卡在第一组batch很久 ![image](https://private-user-images.githubusercontent.com/180263903/368830796-a9725634-134e-48dc-8a9b-f604fe1a289b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjA3ODEsIm5iZiI6MTcyNjcyMDQ4MSwicGF0aCI6Ii8xODAyNjM5MDMvMzY4ODMwNzk2LWE5NzI1NjM0LTEzNGUtNDhkYy04YTliLWY2MDRmZTFhMjg5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNDM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzAwZTI0MjQ3MWVkZWIwODg0OGRlMTVmMzNlNWM2N2ViYjRjZjRmNmQwM2Y0M2JiNjU5ZDA3Y2YwNDgzN2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uAm5sbsmTbUi9_nZ1rjlR7nE-gp9Uq7JVz9KVAAhks8) 经过很长时间报下面的错 Training, Epoch: 0001, Batch: 000032, Sample Num: 32, Cur Loss: 15.14121819, Avg Loss: 20.39010298EI9999: Inner Error! EI9999: 2024-09-19-03:24:21.884.546 The error from device(chipId:0, dieId:0), serial number is 27, hccl fftsplus task timeout occurred during task execution, stream_id:4, sq_id:4, task_id:18848, stuck notify num:1, timeout:1836.[FUNC:ProcessStarsHcclFftsPlusTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1436] TraceBack (most recent call last): The 0 stuck notify wait context info:(context_id=10, notify_id=38).[FUNC:ProcessStarsHcclFftsPlusTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1443] The error from device(chipId:0, dieId:0), serial number is 28, event wait timeout occurred during task execution, stream_id:2, sq_id:2, task_id:57714, event_id=847, timeout=1868.[FUNC:ProcessStarsWaitTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1389] Task execute failed, device_id=0, stream_id=2, task_id=57714, flip_num=2, task_type=3(EVENT_WAIT).[FUNC:GetError][FILE:stream.cc][LINE:1082] rtStreamSynchronize execute failed, reason=[task timeout][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53] synchronize stream failed, runtime result = 107020[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]
> > Inner error, see details in Ascend logs.EH9999: Inner Error! rtStreamSynchronizeWithTimeout execute failed, reason=[task timeout][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53] EH9999: 2024-09-19-03:24:21.928.670 synchronize stream failed, runtime result = 107020[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]
> > 所以我推测是我的参数设置不太对，我尝试了把gradient_accumulation_steps设置为1，好像可以拉起训练，所以想问下这些参数的关系？
> 
> 因为有gradient_accumulation_steps，在trainer.py中，遍历样本时step既要整除loss_logging_steps又要整除gradient_accumulation_steps，所以实际上是每间隔loss_logging_steps与gradient_accumulation_steps最小公倍数个step才输出loss，其他参数也类似
> 
> 你使用的是什么卡？然后看一下project下的exception/下有没有异常信息。或者你修改一下trainer.py， 不使用try-except，这样直接在终端上打印异常信息。 这样就不用等很久才报错误。
> 
> 我修改了trainer.py，能够马上报错，而不用等timeout。已经push到master了，只需要更新trainer.py文件。

是这一段全注释掉吗
![image](https://github.com/user-attachments/assets/5843ee31-d449-4655-bb03-209351a448c0)

**Comment by yyoean** [comment]
现在的报错是NPU out of memory.
Training, Epoch: 0001, Batch: 000006, Sample Num: 6, Cur Loss: 20.49292374, Avg Loss: 22.16985448<frozen importlib._bootstrap>:914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module()
/usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_9_0-0_TableSink1-0-.csv' encoding='utf-8'>
  yield f"{key}_{i}", example
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_22_0-0_TableSink1-0-.csv' encoding='utf-8'>
  yield f"{key}_{i}", example
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/LucaOne/src/trainer.py", line 184, in train
    output = model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/LucaOne/src/models/lucaone_gplm.py", line 526, in forward
    encoding, logits, outputs, losses = self.__forword__(
  File "/home/LucaOne/src/models/lucaone_gplm.py", line 413, in __forword__
    attentions = attentions * attention_mask[:, None, None, :, :]
RuntimeError: NPU out of memory. Tried to allocate 4.88 GiB (NPU 5; 60.97 GiB total capacity; 54.47 GiB already allocated; 54.47 GiB current active; 3.22 GiB free; 57.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

下面是我的npu-smi info
![image](https://github.com/user-attachments/assets/32837786-81b8-490c-9cb3-b02043c83dc7)

**Comment by yyoean** [comment]
> > 现在的报错是NPU out of memory. Training, Epoch: 0001, Batch: 000006, Sample Num: 6, Cur Loss: 20.49292374, Avg Loss: 22.16985448:914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module() :914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module() /usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_9_0-0_TableSink1-0-.csv' encoding='utf-8'> yield f"{key}_{i}", example ResourceWarning: Enable tracemalloc to get the object allocation traceback /usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_22_0-0_TableSink1-0-.csv' encoding='utf-8'> yield f"{key}_{i}", example ResourceWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "/home/LucaOne/src/trainer.py", line 184, in train output = model( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1519, in forward else self._run_ddp_forward(*inputs, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward return self.module(*inputs, **kwargs) # type: ignore[index] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/home/LucaOne/src/models/lucaone_gplm.py", line 526, in forward encoding, logits, outputs, losses = self.**forword**( File "/home/LucaOne/src/models/lucaone_gplm.py", line 413, in **forword** attentions = attentions * attention_mask[:, None, None, :, :] RuntimeError: NPU out of memory. Tried to allocate 4.88 GiB (NPU 5; 60.97 GiB total capacity; 54.47 GiB already allocated; 54.47 GiB current active; 3.22 GiB free; 57.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
> > 下面是我的npu-smi info ![image](https://private-user-images.githubusercontent.com/180263903/368928875-32837786-81b8-490c-9cb3-b02043c83dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mzg5MTksIm5iZiI6MTcyNjczODYxOSwicGF0aCI6Ii8xODAyNjM5MDMvMzY4OTI4ODc1LTMyODM3Nzg2LTgxYjgtNDkwYy05Y2IzLWIwMjA0M2M4M2RjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwOTM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODU0Yjk2ZWY0Y2U0Y2U2ODIyMjQyZDE3YWY5YWUzNmI3NGI2YWFkODE2NDFiZWMzMmY1ZTg1YjRiMDJhOWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lxTpZYnuYrXOj26tp1t6PrxP0p_oluthsN5R_OVXOac)
> 
> > 现在的报错是NPU out of memory. Training, Epoch: 0001, Batch: 000006, Sample Num: 6, Cur Loss: 20.49292374, Avg Loss: 22.16985448:914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module() :914: ImportWarning: TEMetaPathFinder.find_spec() not found; falling back to find_module() /usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_9_0-0_TableSink1-0-.csv' encoding='utf-8'> yield f"{key}_{i}", example ResourceWarning: Enable tracemalloc to get the object allocation traceback /usr/local/lib/python3.10/dist-packages/datasets/iterable_dataset.py:804: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/LucaOne/dataset/lucagplm/v2.0/train/20231124181635210gsp4ebwp2gg_M1_1_22_0-0_TableSink1-0-.csv' encoding='utf-8'> yield f"{key}_{i}", example ResourceWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "/home/LucaOne/src/trainer.py", line 184, in train output = model( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1519, in forward else self._run_ddp_forward(*inputs, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward return self.module(*inputs, **kwargs) # type: ignore[index] File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/home/LucaOne/src/models/lucaone_gplm.py", line 526, in forward encoding, logits, outputs, losses = self.**forword**( File "/home/LucaOne/src/models/lucaone_gplm.py", line 413, in **forword** attentions = attentions * attention_mask[:, None, None, :, :] RuntimeError: NPU out of memory. Tried to allocate 4.88 GiB (NPU 5; 60.97 GiB total capacity; 54.47 GiB already allocated; 54.47 GiB current active; 3.22 GiB free; 57.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
> > 下面是我的npu-smi info ![image](https://private-user-images.githubusercontent.com/180263903/368928875-32837786-81b8-490c-9cb3-b02043c83dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mzg5MTksIm5iZiI6MTcyNjczODYxOSwicGF0aCI6Ii8xODAyNjM5MDMvMzY4OTI4ODc1LTMyODM3Nzg2LTgxYjgtNDkwYy05Y2IzLWIwMjA0M2M4M2RjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwOTM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODU0Yjk2ZWY0Y2U0Y2U2ODIyMjQyZDE3YWY5YWUzNmI3NGI2YWFkODE2NDFiZWMzMmY1ZTg1YjRiMDJhOWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lxTpZYnuYrXOj26tp1t6PrxP0p_oluthsN5R_OVXOac)
> 
> 你的显存不够，我跑的是A100，需要80G显存。你的只有64G。
> 
> 如果你想跑起来，可以降低模型的层数，现在是20层，比如你可以降低到16层，在run_xxx.sh 脚本的NUM_ATTENTION_LAYERS=20参数，顺便也降低NUM_ATTENTION_HEADS的大小，可以按照比例降低 ![image](https://private-user-images.githubusercontent.com/153056894/368933589-3d97a3a0-238d-4c7e-b259-1e6ded2eae99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzkyMDcsIm5iZiI6MTcyNjczODkwNywicGF0aCI6Ii8xNTMwNTY4OTQvMzY4OTMzNTg5LTNkOTdhM2EwLTIzOGQtNGM3ZS1iMjU5LTFlNmRlZDJlYWU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwOTQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGQzOWQ2OWNlZWVkZWM2ODAwZTBlZTBjOTcyZDUwZDgwODMxNTJjMDAwNTI5OTlmMWIwYzNiNDc5OWQ4ZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZkFphYK4eW4Iq7qKdMDYnjDtJhrFrqAqKPBTBLjL55Q)

已解决，非常感谢！
